apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yams-trimble/argocicd.git
    targetRevision: main
    path: helm-chart
    helm:
      releaseName: flask-app
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: flask
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
