FROM python:3.10-slim

RUN apt-get update && apt-get install -y nginx

WORKDIR /app

COPY . /app

RUN pip install flask gunicorn

RUN rm /etc/nginx/sites-enabled/default
COPY nginx.conf /etc/nginx/sites-enabled/

EXPOSE 80

CMD sh -c "gunicorn -w 4 -b 127.0.0.1:5000 app:app & nginx -g 'daemon off;'"