server {
    listen 80;

    location / {
        proxy_pass http://127.0.0.1:5000;

        proxy_set_header Host $host; #forwards the original Host header from the client to the backend server
        proxy_set_header X-Real-IP $remote_addr; #forwards the original client IP address to the backend server
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; #tracks the original client IP address
    }
}