apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: flask-nginx

  template:
    metadata:
      labels:
        app: flask-nginx

    spec:
      containers:
      - name: flask-nginx
        image: docker.io/yams0325/ci-cd:latest
        ports:
        - containerPort: 80